export const GLOSSARY = {
  club: 'Club, as ranked by the standings',
  player: 'Player name — open for the full season and game log',
  dorsal: 'Shirt number as registered for the season',
  ts_pct: 'True shooting % — points per scoring attempt, counting twos, threes and free throws (a trip to the line counts as 0.44 of an attempt)',
  fg3_pct: 'Three-point percentage. Blank below 20 attempts, where the number says more about the sample than the shooter',
  pts36: 'Points per 36 minutes — a rate, so a starter and a bench player are comparable',
  ast36: 'Assists per 36 minutes',
  oreb36: 'Offensive rebounds per 36 minutes',
  dreb36: 'Defensive rebounds per 36 minutes',
  stl36: 'Steals per 36 minutes',
  blk36: 'Blocks per 36 minutes',
  fd36: 'Fouls drawn per 36 minutes',
  tov100: 'Turnovers per 100 possessions — lower is better',
  opp_fg_pct: 'Opponent field-goal % while this player was on court. Five players share every possession, so read it as context rather than as individual defence',
  drtg: 'Opponent points per 100 possessions while this player was on court — lower is better. Team-shared, like Opp FG%',
  pos: 'Registered position: guard, forward or centre',
  ortg: 'Offensive rating — points scored per 100 possessions, so pace does not flatter a fast team',
  drtg_team: 'Defensive rating — points allowed per 100 possessions. Lower is better',
  net_rtg: 'Net rating — offensive minus defensive rating, the margin per 100 possessions',
  efg: 'Effective FG% — field-goal percentage that credits a three as one and a half makes',
  ts_team: 'True shooting % — points per scoring attempt across twos, threes and free throws',
  opp_efg: 'Opponent effective FG%. Lower is better',
  oreb_pct: 'Offensive rebound % — the share of their own misses this club rebounds',
  dreb_pct: 'Defensive rebound % — the share of opponent misses this club rebounds',
  tov_team: 'Turnovers per 100 possessions. Lower is better',
  opp_tov: 'Opponent turnovers forced per 100 possessions',
  ast_team: 'Assists per 100 possessions',
  stl_team: 'Steals per 100 opponent possessions',
  blk_team: 'Blocks per 100 opponent possessions',
  height: 'Height in centimetres, as listed in the club registration',
  country: 'Country on the player registration, which is not always their birthplace',
  opponent: 'Opposing club in this game',
  date: 'Tip-off date (UTC)',
  round: 'Regular-season round number',
  game: 'Open this game — boxscore and score worm',

  gp: 'Games played — games with any court time',
  min: 'Minutes on court, from the official boxscore',
  pts: 'Points scored in the game or season',
  reb: 'Total rebounds — offensive plus defensive',
  ast: 'Assists — a pass leading directly to a made basket',
  stl: 'Steals — possessions taken directly off the opponent',
  to: 'Turnovers — possessions lost without a shot attempt',
  fg2: 'Two-point field goals: made / attempted',
  fg3: 'Three-point field goals: made / attempted',
  ft: 'Free throws: made / attempted',

  w: 'Wins in the regular season',
  l: 'Losses in the regular season',
  pf: 'Points scored across the season',
  pa: 'Points conceded across the season',
  diff: 'Point differential — points scored minus conceded',
  result: 'Win or loss, with the final score',

  pir: 'Performance Index Rating — the official Euroleague formula: (points + rebounds + assists + steals + blocks + fouls drawn) − (missed FG + missed FT + turnovers + shots blocked + fouls committed). Computed here from the boxscore.',
  pir_avg: 'PIR per game played',
  pir_total: 'PIR summed over the season',
  pir_per36: 'PIR scaled to 36 minutes on court — rate rather than volume, so bench players are comparable to starters',

  pm: 'Plus/minus — points scored minus conceded while this player was on court, reconstructed from substitution events in the play-by-play',
  pm_total: 'Plus/minus summed over the season',
  pm_per36: 'Plus/minus scaled to 36 minutes on court',

  clutch_pm: 'Plus/minus in clutch time: the last 5:00 of the 4th quarter or any overtime, while the margin was within 5 points',
  clutch_pts: 'Points scored in clutch time',
  clutch_time: 'Time on court during clutch situations',
  clutch_for: 'Points the club scored in clutch time',
  clutch_against: 'Points the club conceded in clutch time',

  poss: 'Estimated possessions: FGA + 0.44 × FTA − offensive rebounds + turnovers',
  poss_avg: 'Estimated possessions per game — the club’s pace',
  fouls_drawn: 'Fouls drawn (received) from opponents',
  fd100: 'Fouls drawn per 100 possessions — contact drawn at a rate that is comparable between starters and bench players',

  max_run: 'Longest unanswered scoring streak — consecutive points with none conceded',
  run_when: 'When the run started and ended, in game clock',
  max_lead: 'Largest lead held at any point in the game',
  blown_lead: 'Largest lead held in a game the club went on to lose',
  score: 'Final score, home team first',
} as const;

export type MetricKey = keyof typeof GLOSSARY;
