api:
  image:
    repository: elcourtside-api
    tag: dev
    pullPolicy: Never

web:
  image:
    repository: elcourtside-web
    tag: dev
    pullPolicy: Never
  replicaCount: 1

persistence:
  storageClass: standard
  size: 1Gi
  backupSize: 1Gi

backup:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

ingress:
  host: localhost
  tls: false
  clusterIssuer: ""

serviceMonitor:
  enabled: false
